version: "3.9"
services:
  app:
    image: "${docker_repository}/base-api:latest"
    container_name: base-api
    restart: on-failure
    ports: [ "80:80" ]
    logging:
        driver: awslogs
        options:
            awslogs-region: "us-east-1"
            awslogs-group: "base-api"
            awslogs-create-group: "true"
    environment: 
      PORT: 80
      ENV: "prod"
      AWS_DEFAULT_REGION: "us-east-1"
      DB_URL: "postgresql://postgres:postgres@database/base_api"
    links:
      - "postgres:database"

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=base_api
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./volumes/postgres-data:/home/ec2-user/postgres