name: CI

on:
  release:
    types: [created]

  workflow_dispatch:

env:
  APP_NAME: base-api
  FILENAME: base-api.zip
  ZIP_PATH: base-api.zip
  DEPLOYMENT_GROUP: stage
  AWS_REGION: us-east-1


jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kciter/aws-ecr-action@v3
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: ${{ env.APP_NAME }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.sha }}
          create_repo: true

  deploy:
    needs: push-image
    env:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_PATH: ${{ secrets.S3_BUCKET_PATH }}
      S3_KEY: "dev/base-api.zip"
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v2
      - id: deploy
        run: |
          (cd cicd && zip -r ../${{ env.ZIP_PATH }} *)
          zip -ru ${{ env.ZIP_PATH }} docker-compose.prod.yml
          aws s3 cp ${{ env.ZIP_PATH }} ${{ env.S3_PATH }}
          aws deploy create-deployment --application-name ${{ env.APP_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} --description github-triggered --s3-location bucket=${{ env.S3_BUCKET }},bundleType=zip,key=${{ env.S3_KEY }}